$("input").eq(0).click(function(){
    $("#ti").text("");
});
$("input").eq(1).click(function(){
    $("#ti").text("");
});
$("#dl").click(function(event){
     event.preventDefault();
      $.ajax({
        url:"/carrots-admin-ajax/a/login",
        method:"post",
        dataType:"json",
        data:"name="+$("input").eq(0).val()+"&pwd="+$("input").eq(1).val(),
        async:"true",
        success:function(data){
            if(data.code===0){
                window.location.href = "http://dev.admin.carrots.ptteng.com/";
            }else{
                $("#ti").text(data.message)
            }
        },
        error:function(){
            $("#ti").text("暂时无法登陆")
        }
      })
})